export const ROUTES = {
  LOGIN: {
    LOGIN: "/smember",
    REGISTER: "/smember/register",
  },

  MEMBER: {
    HOMEPAGE: "/smember/homepage",
    ORDER: "/smember/order",
    PROMOTION: "/smember/promotion",
    RANK: "/smember/rank",
    ACCOUNT_INFO: "/smember/account/user-info",
    CHANGE_PASSWORD: "/smember/change-password",
    ACCOUNT_SUPPORT: "/smember/account/support",
    ACCOUNT_FEEDBACK: "/smember/account/feedback",
  },

  CART: {
    CART_PAGE: "/cart",
  },

  HOME: {
    HOME: "/",
    HOME_MOBILE: "/mobile",
    HOME_LAPTOP: "/laptop",
    HOME_TABLET: "/tablet",
    HOME_AUDIO: "/thiet-bi-am-thanh",
    HOME_CLOCK: "/do-choi-cong-nghe",
    HOME_SMART_HOME: "/nha-thong-minh",
    HOME_ACCESSORIES: "/phu-kien",
    HOME_PC: "/may-tinh-de-ban",
    HOME_TV: "/tivi",
    HOME_PURCHASE: "/thu-cu-doi-moi",
    HOME_SECONDHAND: "/hang-cu",
    HOME_SALE: "/danh-sach-khuyen-mai",
    HOME_TECH_INFO: "/sforum",
    HOME_DIENTHOAIVUI: "/dienthoaivui",
    HOME_ASP: "/ASP",
    PRODUCT_LIST: "/products",
    PRODUCT_DETAIL: "/product/:id",
  },
  ADMIN: {
    ADMIN_HOME: "/admin",
    ADMIN_PRODUCT_LIST: "/admin/products",
    ADMIN_CREATE_PRODUCT: "/admin/product/create",
    ADMIN_INSERT_IMAGE_PRODUCT: "/admin/product/insert-image",
    ADMIN_INSERT_INFO_PRODUCT: "/admin/product/insert-info",
    ADMIN_UPDATE_PRODUCT: "/admin/product/:id/update",
    ADMIN_CATEGORY_LIST: "/admin/categories",
    ADMIN_USER_LIST: "/admin/users",
    ADMIN_CREATE_USER: "/admin/user/create",
    ADMIN_UPDATE_USER: "/admin/user/:id/update",
    ADMIN_SUPER_LIST: "/admin/supers",
    ADMIN_STORE_LIST: "/admin/stores",
    ADMIN_INVOICE_LIST: "/admin/invoices",
    ADMIN_NOTIFICATION: "/admin/notifications",
    ADMIN_SETTING: "/admin/setting",
  },
};
